"""Sample files for the second tutorial, generated on demand.

The import modules teach real procedures, so the learner needs real files to
feed the real importers — not screenshots of someone else doing it. Generating
them here (rather than committing binaries) keeps them aligned with whatever
the importers currently accept: the round-trip is pinned by tests that push
these exact bytes through the real import code.

Everything is fictional and scoped to the sandbox dataset: the CSP introduces a
qualification that does not exist in the sandbox, and the preferences workbook
names two sandbox lecturers whose availability no other tutorial module leans
on (Steve Irwin's Mon–Wed window is module 5's teaching material — his sheet
deliberately is not here).
"""
from __future__ import annotations

import io

from docx import Document
from docx.shared import Pt
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill

from timetable.constants import DAYS, slot_to_time

# ---------------------------------------------------------------------------
# CSP document
# ---------------------------------------------------------------------------

SAMPLE_CSP_QUALIFICATION = "22334VIC Certificate IV in Cyber Operations"
SAMPLE_CSP_FILENAME = f"CSP_{SAMPLE_CSP_QUALIFICATION}.docx"

#: (class name, hours, [unit codes]) per semester table. One class carries two
#: unit codes, so the import demonstrates continuation rows.
SAMPLE_CSP_STAGES: list[list[tuple[str, int, list[str]]]] = [
    [
        ("Cyber Operations Fundamentals", 4, ["VU23301"]),
        ("Networking Essentials", 3, ["VU23302", "VU23303"]),
        ("Linux Command Line", 2, ["VU23304"]),
    ],
    [
        ("Security Operations Centre", 4, ["VU23305"]),
        ("Digital Forensics Basics", 3, ["VU23306"]),
        ("Industry Project (Cyber)", 2, ["VU23307"]),
    ],
]

SAMPLE_CSP_CLASS_COUNT = sum(len(stage) for stage in SAMPLE_CSP_STAGES)


def build_sample_csp_docx() -> bytes:
    """A small, well-formed CSP: title, semester headings, SIN/TPN tables.

    Written in exactly the shape ``csp_qualification_import`` parses — the
    header row must carry SIN and TPN, column 0 is "Name | Nhrs", column 2 is
    the unit code, and a blank column 0 continues the class above.
    """
    doc = Document()
    title = doc.add_paragraph(SAMPLE_CSP_QUALIFICATION)
    title.runs[0].bold = True
    title.runs[0].font.size = Pt(14)
    doc.add_paragraph(
        "Curriculum Structure Package — sample document generated by the "
        "TAFEtabler tutorial."
    )

    for index, stage in enumerate(SAMPLE_CSP_STAGES, start=1):
        doc.add_paragraph(f"Semester {index}")
        table = doc.add_table(rows=1, cols=3)
        table.style = "Table Grid"
        for col, text in enumerate(["Class", "SIN", "TPN"]):
            table.rows[0].cells[col].text = text
        for name, hours, codes in stage:
            for position, code in enumerate(codes):
                row = table.add_row()
                row.cells[0].text = f"{name} | {hours}hrs" if position == 0 else ""
                row.cells[1].text = ""
                row.cells[2].text = code
        doc.add_paragraph("")

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


# ---------------------------------------------------------------------------
# Lecturer preferences workbook
# ---------------------------------------------------------------------------

SAMPLE_PREFS_FILENAME = "Lecturer preferences (tutorial sample).xlsx"

_CYBER_QUAL = "Certificate IV in Cyber Security — 22603VIC"

#: Per lecturer: (preference rows, non-teaching day). Blocked times are the
#: same for both — evenings, which no sandbox booking touches, so the import
#: rewrites availability without manufacturing warnings.
SAMPLE_PREFS: dict[str, tuple[list[tuple[str, str, str]], str]] = {
    "Keanu Reeves": (
        [
            ("First", _CYBER_QUAL, "Secure Programming Basics — VU23225"),
            ("First", _CYBER_QUAL, "Cyber Threat Intelligence — VU23223"),
            ("Second", _CYBER_QUAL, "Network Security Fundamentals — VU23217"),
            ("Third", _CYBER_QUAL, "Workplace Communication — BSBXCM301"),
        ],
        "Friday",
    ),
    "Stephen Hawking": (
        [
            ("First", _CYBER_QUAL, "Network Security Fundamentals — VU23217"),
            ("Second", _CYBER_QUAL, "Cyber Threat Intelligence — VU23223"),
            ("Third", _CYBER_QUAL, "Secure Programming Basics — VU23225"),
        ],
        "Friday",
    ),
}

#: Evening half-hours, 18:00 onwards — slots 20..27 of the 28-slot day.
_BLOCKED_SLOTS = range(20, 28)


def build_sample_preferences_xlsx() -> bytes:
    """A filled-in preferences workbook, one sheet per lecturer.

    Only the cells the importer reads matter — title in A1, preference rows at
    6..11, non-teaching day in B14, and a blocked grid keyed on time labels in
    column A — but the sheet is laid out to read like the real template, since
    the learner is expected to open it before importing.
    """
    wb = Workbook()
    wb.remove(wb.active)
    head = Font(bold=True)
    block_fill = PatternFill(start_color="FFFCE4EC", end_color="FFFCE4EC", fill_type="solid")

    for staff_name, (prefs, non_teaching) in SAMPLE_PREFS.items():
        ws = wb.create_sheet(staff_name[:31])
        ws["A1"] = f"Preferences — {staff_name}"
        ws["A1"].font = Font(bold=True, size=13)

        ws["A5"] = "Priority"
        ws["B5"] = "Qualification"
        ws["C5"] = "Class"
        for cell in ("A5", "B5", "C5"):
            ws[cell].font = head
        for offset, (priority, qual, cls) in enumerate(prefs):
            row = 6 + offset  # the importer reads rows 6..11
            ws.cell(row=row, column=1, value=priority)
            ws.cell(row=row, column=2, value=qual)
            ws.cell(row=row, column=3, value=cls)

        ws["A14"] = "Non-teaching day"
        ws["A14"].font = head
        ws["B14"] = non_teaching

        ws["A20"] = "Blocked times (X = unavailable)"
        ws["A20"].font = head
        for day_index, day in enumerate(DAYS):
            cell = ws.cell(row=21, column=2 + day_index, value=day)
            cell.font = head
        for row_offset, slot in enumerate(_BLOCKED_SLOTS):
            row = 22 + row_offset
            start = slot_to_time(slot).strftime("%H:%M")
            end = slot_to_time(slot + 1).strftime("%H:%M")
            label = f"{start}–{end}"
            ws.cell(row=row, column=1, value=label)
            for day_index in range(len(DAYS)):
                cell = ws.cell(row=row, column=2 + day_index, value="X")
                cell.fill = block_fill
        ws.column_dimensions["A"].width = 22
        for col in "BCDEF":
            ws.column_dimensions[col].width = 14
        ws.column_dimensions["B"].width = 40
        ws.column_dimensions["C"].width = 44

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()
